version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/application
      - static_volume:/static  # <-- bind the static volume
      - media_volume:/media  # <-- bind the media volume
    depends_on:
      - postgres
    networks:
      - nginx_network
      - postgres
    env_file:
      - .env
    command: ["sh" , "entrypoint.sh"]

  nginx:
    image: nginx:1.13
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/static  # <-- bind the static volume
      - media_volume:/media  # <-- bind the media volume
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  postgres:
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    networks:
      - postgres
    env_file:
      - .env

networks:
  nginx_network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
